version: '3.9'
services:
  rest_api:
    container_name: ${APP_NAME}api
    image: yaric011/waffler_server_test:latest
    restart: always
    volumes:
      - ../.env:/root/.env
      - ../telegram_sessions:/root/telegram_sessions
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - skynet

  db:
    container_name: ${APP_NAME}db
    image: postgres:14.4-alpine
    restart: always
    volumes:
      - db-data:/root/telegram
    env_file:
      - ../.env

    networks:
      - skynet
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db-data:
networks:
  skynet: