version: '3.9'
services:
  rest_api_test:
    container_name: ${APP_NAME}api_test
    image: yaric011/waffler_server_test:latest
    restart: always
    volumes:
      - ../.env:/root/.env
      - ../telegram_sessions:/root/telegram_sessions
    depends_on:
      - db_test
    ports:
      - 8081:8080
    networks:
      - skynet_test

  db_test:
    container_name: ${APP_NAME}db_test
    image: postgres:14.4-alpine
    restart: always
    volumes:
      - db-data_test:/root/telegram
    env_file:
      - ../.env
    networks:
      - skynet_test
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db-data_test:
networks:
  skynet_test: