version: '3.9'
services:
  ratesapi:
    container_name: ${APP_NAME}api
    image: yaric011/waffler_server:latest
    restart: always
    volumes:
      - telegram-data:/var/lib/postgresql/data
      - .env:/root/.env
    depends_on:
      - db

    ports:
      - 8080:8080
    networks:
      - skynet

  db:
    container_name: ${APP_NAME}db
    image: postgres:14.4-alpine
    restart: always
    volumes:
      - db-data:/root/telegram_sessions
    env_file:
      - .env
    ports:
      - ${HOST}:${DB_PORT}:${DB_PORT}
    networks:
      - skynet
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  telegram-data:
  db-data:
networks:
  skynet: