version: '3.9'
services:
  db:
    container_name: ${APP_NAME}db
    image: postgres:14.4-alpine
    restart: always
    volumes:
      - ../db{APP_NAME}:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    ports:
      - ${HOST}:${DB_PORT}:${DB_PORT}
    networks:
      - skynet
    logging:
      options:
        max-size: "10m"
        max-file: "3"
networks:
  skynet: